package com.design.dashboard;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Dashboard extends VerticalLayout {
	protected CssLayout header_bar;
	protected Button clear;
	protected ComboBox select;
	protected HorizontalLayout main_area;
	protected CssLayout side_bar;
	protected NativeButton usageButton;
	protected NativeButton mapsButton;
	protected NativeButton mathButton;
	protected NativeButton newsButton;
	protected NativeButton weatherButton;
	protected NativeButton queryButton;
	protected NativeButton databaseButton;
	protected Panel scroll_panel;

	public Dashboard() {
		Design.read(this);
	}
}
